server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nguyenphuocthanhit-byte/microservices-system
          default-label: main
          search-paths: config-repo  # QUAN TRỌNG: chỉ định thư mục config
          clone-on-start: true
          force-pull: true

eureka:
  client:
    service-url:
#      defaultZone: http://eureka-server:8761/eureka
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always