spring:
  application:
    name: order-service

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 2000
        max-interval: 10000
        multiplier: 1.5

logging:
  level:
    org.springframework.cloud.config: INFO
    org.springframework.boot.context.config: INFO
